# Generated by release/render_formula.py from release/formula/stems.rb.tmpl
# (stems deliverable 32). Do not edit in the tap: the release workflow
# overwrites this file on every release.
class Stems < Formula
  desc "Local environment management toolkit for multi-process systems"
  homepage "https://github.com/humbertopoliti/stems"
  version "0.2.0"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/humbertopoliti/stems/releases/download/v0.2.0/stems-cli-aarch64-apple-darwin.tar.xz"
      sha256 "af8a2d7feb259d93da45b34223a226d74c6c593c38eea629b484453c5a80259e"
    end
    on_intel do
      url "https://github.com/humbertopoliti/stems/releases/download/v0.2.0/stems-cli-x86_64-apple-darwin.tar.xz"
      sha256 "74a020d3f21e5d1f45a9a468b1a5f4fb9b4f2554d383ad8d86a7aa2e95db7b88"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/humbertopoliti/stems/releases/download/v0.2.0/stems-cli-aarch64-unknown-linux-gnu.tar.xz"
      sha256 "468c7e265ad87e004b027cbf82547b1f972c833a4bba535e07394b537837b7f3"
    end
    on_intel do
      url "https://github.com/humbertopoliti/stems/releases/download/v0.2.0/stems-cli-x86_64-unknown-linux-gnu.tar.xz"
      sha256 "79fe1bb742eaf743e6b799dda38568009865472a9295c9bf5d8199a4fb903307"
    end
  end

  def install
    # The daemon is the same binary (`stems daemon`): one artifact.
    bin.install "stems"
    bash_completion.install "completions/stems.bash" => "stems"
    zsh_completion.install "completions/_stems"
    fish_completion.install "completions/stems.fish"
    man1.install Dir["man/*.1"]
  end

  def caveats
    <<~EOS
      After `brew upgrade stems`, restart running workspace daemons
      (`stems daemon stop`; the next command starts the new one).
    EOS
  end

  test do
    assert_match "stems #{version}", shell_output("#{bin}/stems --version")
    (testpath/"stems.yaml").write <<~YAML
      schema_version: 1
      name: brew-test
      stems:
        hello:
          type: process
          command: sleep 30
    YAML
    ENV["STEMS_HOME"] = (testpath/"home").to_s
    system bin/"stems", "validate", "--skip-requires", "--workspace", testpath
  end
end
