# Generated by release/render_formula.py from release/formula/stems.rb.tmpl
# (stems deliverable 32). Do not edit in the tap: the release workflow
# overwrites this file on every release.
class Stems < Formula
  desc "Local environment management toolkit for multi-process systems"
  homepage "https://github.com/humbertopoliti/stems"
  version "0.3.0"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/humbertopoliti/stems/releases/download/v0.3.0/stems-cli-aarch64-apple-darwin.tar.xz"
      sha256 "dbdb6fd31e82107f751221342f328b72006decfdd29f24418d7ce15ae8aebdd7"
    end
    on_intel do
      url "https://github.com/humbertopoliti/stems/releases/download/v0.3.0/stems-cli-x86_64-apple-darwin.tar.xz"
      sha256 "590c7962d52162589243a2df8d82f4deb65ec33eeea6968f44153d9878cca674"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/humbertopoliti/stems/releases/download/v0.3.0/stems-cli-aarch64-unknown-linux-gnu.tar.xz"
      sha256 "535c8f1deed34a7841df7dbbfc7bd187c19687ec87904e4c2affc2118a54e9d4"
    end
    on_intel do
      url "https://github.com/humbertopoliti/stems/releases/download/v0.3.0/stems-cli-x86_64-unknown-linux-gnu.tar.xz"
      sha256 "a278390bfdff20caba6cdb31bd919cab545cc175e8a9139a6399b6fa96d44ca4"
    end
  end

  def install
    # The daemon is the same binary (`stems daemon`): one artifact.
    bin.install "stems"
    bash_completion.install "completions/stems.bash" => "stems"
    zsh_completion.install "completions/_stems"
    fish_completion.install "completions/stems.fish"
    man1.install Dir["man/*.1"]
  end

  def caveats
    <<~EOS
      After `brew upgrade stems`, restart running workspace daemons
      (`stems daemon stop`; the next command starts the new one).
    EOS
  end

  test do
    assert_match "stems #{version}", shell_output("#{bin}/stems --version")
    (testpath/"stems.yaml").write <<~YAML
      schema_version: 1
      name: brew-test
      stems:
        hello:
          type: process
          command: sleep 30
    YAML
    ENV["STEMS_HOME"] = (testpath/"home").to_s
    system bin/"stems", "validate", "--skip-requires", "--workspace", testpath
  end
end
