# Generated by release/render_formula.py from release/formula/stems.rb.tmpl
# (stems deliverable 32). Do not edit in the tap: the release workflow
# overwrites this file on every release.
class Stems < Formula
  desc "Local environment management toolkit for multi-process systems"
  homepage "https://github.com/humbertopoliti/stems"
  version "0.1.0"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/humbertopoliti/stems/releases/download/v0.1.0/stems-cli-aarch64-apple-darwin.tar.xz"
      sha256 "b2ff82b0b25133b0a56818d842327cc03ac390ce655d2a80d242bab8a5b9e447"
    end
    on_intel do
      url "https://github.com/humbertopoliti/stems/releases/download/v0.1.0/stems-cli-x86_64-apple-darwin.tar.xz"
      sha256 "d5e87fac3f7a2268d1eeb3303a9ec8d089aa10f35dd0e8bf8279138d63af977e"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/humbertopoliti/stems/releases/download/v0.1.0/stems-cli-aarch64-unknown-linux-gnu.tar.xz"
      sha256 "663ce47728c0f4fe24b6f2070ce2713f9cb837903428bec5e0086a6c849e3706"
    end
    on_intel do
      url "https://github.com/humbertopoliti/stems/releases/download/v0.1.0/stems-cli-x86_64-unknown-linux-gnu.tar.xz"
      sha256 "e31d3a425aa1e182176ec109ff4666566f98b9c85b6cd891fcecc778323a6096"
    end
  end

  def install
    # The daemon is the same binary (`stems daemon`): one artifact.
    bin.install "stems"
    bash_completion.install "completions/stems.bash" => "stems"
    zsh_completion.install "completions/_stems"
    fish_completion.install "completions/stems.fish"
    man1.install Dir["man/*.1"]
  end

  def caveats
    <<~EOS
      After `brew upgrade stems`, restart running workspace daemons
      (`stems daemon stop`; the next command starts the new one).
    EOS
  end

  test do
    assert_match "stems #{version}", shell_output("#{bin}/stems --version")
    (testpath/"stems.yaml").write <<~YAML
      schema_version: 1
      name: brew-test
      stems:
        hello:
          type: process
          command: sleep 30
    YAML
    ENV["STEMS_HOME"] = (testpath/"home").to_s
    system bin/"stems", "validate", "--skip-requires", "--workspace", testpath
  end
end
